### ISSUE TITLE
Performance lower than MixVPR?

### ISSUE THREAD

**Issue by xushangnjlh** [amaralibey/OpenVPRLab#3]
I trained with the provided mixvpr_restnet50 config, seems the result (~0.85 in msls-val) is lower than MixVPR repo's training result (~0.87)? why?

**Comment by amaralibey** [comment]
Hello @xushangnjlh 

That's because in the yaml file you used, the out_channel of MixVPR is initialized to 512 (the default value). While the paper uses 1024.
I just tried training with the below configuration and I got ~0.875 r@1.

Here is the parameter I changed in the `mixvpr_resnet50.yaml` file:
```
aggregator:
  module: src.models.aggregators
  class: MixVPR # class name
  params:
    in_channels:  
    in_h: 20           
    in_w: 20
    out_channels: 1024 # <==== CHANGE TO 1024 for best performance
    mix_depth: 4
    mlp_ratio: 1
    out_rows: 4
```
